config/routes.rb
Rails.application.routes.draw do
  root 'titles#index'

  resources :titles
end

app/models/author.rb
class Author < ActiveRecord::Base
	belongs_to :title
end

app/models/genre.rb
class Genre < ActiveRecord::Base
	belongs_to :title
end

app/models/title.rb
class Title < ActiveRecord::Base
	has_one :author, dependent: :destroy
	has_one :genre, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
  def index
  	@titles = Title.all
  end

  def show
  	@title = Title.find(params[:id])
  end

  def edit
  	#GET--should hsow a form to edit a school
  	@title = Title.find(params[:id])
  end  


	def update
  	@title = Title.find(params[:id])
	  if @school.update(title_params)
	    redirect_to title_path
	  else
	    render :edit
	  end
	end

  def new
  	@title = Title.new
  end

  def create
		# POST---this will create a new book title in
		@title = Title.new(title_params)
		if @title.save
			redirect_to titles_path
		else
			render :new
		end	
  end

  def destroy
  	#method is responsible for deleting single title out of the database
		Title.find(params[:id]).destroy
		redirect_to title_path  
  end

  
  private

  def title_params
  	params.require(:title).permit(:title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/titles_helper.rb
module TitlesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Odot2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/titles/_form.html.erb
<%= form_for @title do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %> 
	
	<%= f.label :author %>
	<%= f.text_field :author%>

	<%= f.label :genre %>
	<%= f.text_field :genre%>

	<%= f.submit %>
<%end%>

app/views/titles/edit.html.erb
<h1>Edit Book Title: <%= @title.name %> </h1>
<br />

<%= render(partial: "form") %>

app/views/titles/index.html.erb
<h1>Your Reading List</h1>
<hr/>

<!--what does the user see if ther are no schools?-->
<!--what does the user see if there are schools?-->
<!--add a link or a button to create  anew school-->	

<% if @titles.any? %>
	<!--loop the schools and diplay links to each one-->
	<ul>
		<% @titles.each do |title|%>
		  <li>
		    <%=link_to title.name, title_path(title)%>
		    <!-- <a href='/school/:id'>Neumont</a> is what the above link is doing-->
		  </li>
    <%end%>
  </ul>
<% else %>
  <h3>No book titles found. Please create one!</h3>
<%end%>

<%=link_to 'New Title', new_title_path %>

app/views/titles/new.html.erb
<h1>Enter your first book title:</h1>
<hr/>


<%= render(partial: "form") %> 

app/views/titles/show.html.erb
<h1><%= @title.name%> Info:</h1>
<hr />

<h3>
	This book was written by: <%= @title.author %>
</h3>

<h3>
The genre is: <%= @title.genre %>
</h3>

<%= link_to 'All_titles', title_path %>
<%= link_to 'Edit', edit_title_path %>
<%= link_to 'Delete', title_path, method: :delete %>